### ISSUE TITLE
Kailh low profile sockets

### ISSUE THREAD

**Issue by xeaone** [Duckle29/Vitamins-included#1]
Hello awesome project products. I have been ordering parts from novel keys. 

Does this board support Kailh low profile sockets?

**Comment by Duckle29** [comment]
It uses the (currently sold out) MX sockets: https://novelkeys.xyz/products/kailh-pcb-sockets

**Comment by xeaone** [comment]
Bummer. Do you have or know of any other PCB designs that use the kailh low profile choc sockets?

Thanks!

**Comment by Duckle29** [comment]
None that I'm aware of, sorry
