### ISSUE TITLE
ISP and unknown components

### ISSUE THREAD

**Issue by happenslol** [Duckle29/Vitamins-included#3]
Hey man, first of all, huge thanks for putting this out here! It's been a big help to me in working on my own keyboard PCB design. However, I had a few questions about the components you're using for this project and was hoping you could help me out.

First of all, if I understand correctly, the "ISP" pins (J3 and J6 in the schematic) are used to flash a chip without a bootloader. However, I can't see anywhere what type of ISP and what type of connector is actually used to connect to this. Is it just a generic ISP programmer and the pins are soldered to? Or is there an actual connector that can be used for this?

The second thing is the parts D27 and D28. Your BOM only annotates these with "red" - does this mean any red LED will do here? I assume that this is just to indicate power to the PCB, is that correct?

My last question is about the parts P3 and P6. These have the annotation "WS2812", but they do not appear on the BOM. They are hooked into the same circuit the LEDs and the name fits too, so I assume these are LEDs too, but they don't fit the footprint of a WS2812 and don't have enough pins. What are these meant to be used for?

Thanks in advance for any answers you can give me. I'd gladly make a PR with more annotations to these parts if you tell me about them, so that's it's easier to get a hold of all components needed to build this board for other people too.

**Comment by Duckle29** [comment]
Hey there.

The ISP footprints are designed for use with a [TC2030-NL probe](http://www.tag-connect.com/node/23)

It allows for just an SMD footprint and as such ads no cost to the board. You can see it demonstrated [here](https://www.youtube.com/watch?v=dtch7CDxHiI).
The previous version used a normal 2x3 0.1" header, and a pogo-pin jig I printed. 

As for D27 and D28, those are just red LEDs, I'll let my boardhouse pick the cheapest they can find. They're used by QMK-DFU to give primitive status indication :)

P3 and P6 are meant to be used for extending the onboard WS2812 string.  
If you have the latest version, you can see that I added some jumpers that'll allow you to configure how the onboard LEDs are connected. The standard being MCU -> onboard -> P3/P6, however, they can be configured in other ways (described on a qmk.fm page that I'm waiting to make a PR for until these have gone through production :) )

If you're looking at making a batch of this particular repo, be aware that the files are untested, and some issues (rotated ws2812 footprints) have only recently been resolved, as we are moving to have 100 made. Additionally, the  USB-C connector is a bit hard to source but is used as it is a good quality connector that my boardhouse can source cheaply. 

As for a timeframe, I'd say a few months.

**Comment by happenslol** [comment]
Thanks for the super quick response!
That clears it up. I'll probably just get a simple AVR programmer then and use one of those connectors. Nice work on the programmer in that video though, I especially love that switch used to start the flashing =) Should put a keycap on it though...

And thanks for the heads up, I've made my own pcb and taken a lot from this schematic and the original let's split, but I won't be using these files directly. I've also replaced the USB connector already, it was pretty much impossible to find yours through google.

Do you want me to add more descriptions/comments to the mentioned parts and make a PR?

**Comment by Duckle29** [comment]
Ah cool. Yeah the connector is solidly a "made in china" part, and sold in quantities that doesn't make sense for most people :)

I don't really see how you'd add those descriptions comments, and I probably wouldn't merge the PR, so I don't want to waste your time on it :)

Something like the BOM for the LEDs might be updated, so far the fab told me it was good enough for a quote, but they need more specific part numbers for some of the parts, so the BOM should be updated before production starts.

As for the programming header, the footprint is named TC2030 iirc, but as it's not an actual component, it's not present in the position files or the BOM. 

The usage of P3 and P6 will be described on qmk.fm once I make a PR for [these](https://github.com/Duckle29/qmk.fm/blob/gh-pages/_pages/keyboards/vitamins_included.md) changes :)

**Comment by happenslol** [comment]
My idea would've been to just add another field to the symbol properties in the schematic, and maybe add the links you provided as the datasheet, just to point people in the right direction. Otherwise, I would've just added the information to the README, but it's ok if you're just using this repo for yourself anyways.

Thanks again for all the information, and the PR link. I'll be watching the stock for the board and probably pick one up when you do that production run =)

**Comment by Duckle29** [comment]
I updated the BOM for the LEDs, I found some nicely priced ones, and figured I might as well :)

As for the TC2030, adding that link as the datasheet would be fine :) As for the use of the P3 and P6, I think the qmk.fm page describes that fairly well, and I don't think that fits this repo.

This repo is meant to hold all the files necessary to produce these boards, and I'd keep the documentation of its use elsewhere (qmk.fm if allowed :) )
